FROM ruby:3.4.1

WORKDIR /rails

RUN apt-get update -qq && apt-get install -y \
  build-essential \
  sqlite3 \
  nodejs \
  yarn

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

EXPOSE 3000

CMD ["bash", "-c", "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0"]
